# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  ostree:
    taskfile: "~/.config/tasks/ostree.yml"
  edit:
    taskfile: "~/.config/tasks/edit.yml"
  install:
    taskfile: "~/.config/tasks/install.yml"
tasks:
  pkg-search:
    cmd: "nohup xdg-open 'https://search.nixos.org/packages' >/dev/null 2>&1"
