services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    # networks: [traefik_default]
    container_name: syncthing
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ~/.config/syncthing:/config
      - ~/shared:/config/shared
      - ~/projects:/config/projects
    network_mode: host
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.rule: Host(`syncthing.local.dvyy.me`)
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
networks:
  traefik_default:
    external: true
