services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ~/.config/syncthing:/config
      - ~/shared:/config/shared
      - ~/projects:/config/projects
    ports: [ "8384:8384", "22000:22000/tcp", "22000:22000/udp", "21027:21027/udp" ]
    restart: always
